# coding: utf-8

"""
    Pure Storage FlashBlade REST Client

    Client for FlashBlade REST API 1.0, developed by Pure Storage, Inc. (http://www.purestorage.com/).

    OpenAPI spec version: 1.0
    Contact: info@purestorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class FileSystemRules(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, nfs=None, http=None, smb=None):
        """
        FileSystemRules - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'nfs': 'NfsRule',
            'http': 'ProtocolRule',
            'smb': 'ProtocolRule'
        }

        self.attribute_map = {
            'nfs': 'nfs',
            'http': 'http',
            'smb': 'smb'
        }

        self._nfs = nfs
        self._http = http
        self._smb = smb

    @property
    def nfs(self):
        """
        Gets the nfs of this FileSystemRules.
        NFS configuration. Modifiable.

        :return: The nfs of this FileSystemRules.
        :rtype: NfsRule
        """
        return self._nfs

    @nfs.setter
    def nfs(self, nfs):
        """
        Sets the nfs of this FileSystemRules.
        NFS configuration. Modifiable.

        :param nfs: The nfs of this FileSystemRules.
        :type: NfsRule
        """

        self._nfs = nfs

    @property
    def http(self):
        """
        Gets the http of this FileSystemRules.
        HTTP configuration. Modifiable.

        :return: The http of this FileSystemRules.
        :rtype: ProtocolRule
        """
        return self._http

    @http.setter
    def http(self, http):
        """
        Sets the http of this FileSystemRules.
        HTTP configuration. Modifiable.

        :param http: The http of this FileSystemRules.
        :type: ProtocolRule
        """

        self._http = http

    @property
    def smb(self):
        """
        Gets the smb of this FileSystemRules.
        SMB configuration. Modifiable.

        :return: The smb of this FileSystemRules.
        :rtype: ProtocolRule
        """
        return self._smb

    @smb.setter
    def smb(self, smb):
        """
        Sets the smb of this FileSystemRules.
        SMB configuration. Modifiable.

        :param smb: The smb of this FileSystemRules.
        :type: ProtocolRule
        """

        self._smb = smb

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, FileSystemRules):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
