# coding: utf-8

"""
    Purity//FB REST Client

    Client for Purity//FB REST API 1.0, developed by [Pure Storage, Inc](http://www.purestorage.com/). Documentations can be found at [purity-fb.readthedocs.io](http://purity-fb.readthedocs.io/en/latest/).

    OpenAPI spec version: 1.0
    Contact: info@purestorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ObjectResponse(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, items=None, pagination_info=None):
        """
        ObjectResponse - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'items': 'list[PureObject]',
            'pagination_info': 'PaginationInfo'
        }

        self.attribute_map = {
            'items': 'items',
            'pagination_info': 'pagination_info'
        }

        self._items = items
        self._pagination_info = pagination_info

    @property
    def items(self):
        """
        Gets the items of this ObjectResponse.
        a list of objects

        :return: The items of this ObjectResponse.
        :rtype: list[PureObject]
        """
        return self._items

    @items.setter
    def items(self, items):
        """
        Sets the items of this ObjectResponse.
        a list of objects

        :param items: The items of this ObjectResponse.
        :type: list[PureObject]
        """
        if items is None:
            raise ValueError("Invalid value for `items`, must not be `None`")

        self._items = items

    @property
    def pagination_info(self):
        """
        Gets the pagination_info of this ObjectResponse.
        pagination information

        :return: The pagination_info of this ObjectResponse.
        :rtype: PaginationInfo
        """
        return self._pagination_info

    @pagination_info.setter
    def pagination_info(self, pagination_info):
        """
        Sets the pagination_info of this ObjectResponse.
        pagination information

        :param pagination_info: The pagination_info of this ObjectResponse.
        :type: PaginationInfo
        """

        self._pagination_info = pagination_info

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ObjectResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
